# Generated by Django 3.2 on 2023-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('moderator', 'Moderator'),
                    ('user', 'User'),
                ],
                default='user',
                max_length=20,
                verbose_name='Роль',
            ),
        ),
    ]
