# Generated by Django 3.2 on 2023-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_auto_20231212_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
