# Generated by Django 3.2 on 2023-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0003_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
