# Generated by Django 3.2 on 2023-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0004_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
