# Generated by Django 3.2 on 2023-12-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0005_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
