# Generated by Django 3.2 on 2023-12-16 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Оценка не может превышать 10.'), django.core.validators.MinValueValidator(limit_value=1, message=('Оценка не может быть меньше 1.',))], verbose_name='Оценка произведению'),
        ),
    ]
